ext {
    navigationArtifactGroupId = 'io.github.track-asia'
    navigationArtifactId = 'android'
    navigationArtifactTitle = 'TrackAsia Navigation SDK for Android'
    navigationArtifactDescription = 'TrackAsia Navigation SDK for Android'
    navigationDeveloperName = 'TrackAsia'
    navigationDeveloperId = 'trackasia'
    navigationDeveloperMail = 'trackasia@track-asia.com'
    navigationArtifactUrl = 'https://github.com/track-asia/trackasia-navigation-android'
    navigationArtifactScmUrl = 'scm:git@github.com:trackasia/trackasia-navigation-android.git'
    navigationArtifactLicenseName = 'MIT'
    navigationArtifactLicenseUrl = 'https://opensource.org/license/MIT'
    versionName = project.hasProperty('VERSION_NAME') ? project.property('VERSION_NAME') : System.getenv('VERSION_NAME')
}
