# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

target 'ML Nav - iOS Sample App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TrackAsia', '~> 6.10.0'
  pod 'TrackAsiaNavigationCore', :path => '../../trackasia-navigation-core/build/cocoapods/publish/debug'
  
  pod 'Alamofire', '~> 5.10.2'
  
end
